-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.business_competitors_fixed (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  business_id uuid NOT NULL,
  rank smallint NOT NULL CHECK (rank >= 1 AND rank <= 4),
  competitor_external_place_id uuid NOT NULL,
  competitor_name text,
  competitor_rating_value numeric,
  competitor_rating_votes integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT business_competitors_fixed_pkey PRIMARY KEY (id),
  CONSTRAINT business_competitors_fixed_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT business_competitors_fixed_competitor_external_place_id_fkey FOREIGN KEY (competitor_external_place_id) REFERENCES public.external_places(id)
);
CREATE TABLE public.businesses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_user_id uuid NOT NULL,
  external_place_id uuid NOT NULL,
  plan text NOT NULL DEFAULT 'trial'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT businesses_pkey PRIMARY KEY (id),
  CONSTRAINT businesses_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES auth.users(id),
  CONSTRAINT businesses_external_place_id_fkey FOREIGN KEY (external_place_id) REFERENCES public.external_places(id)
);
CREATE TABLE public.external_places (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  google_place_id text,
  google_cid text,
  feature_id text,
  tripadvisor_url_path text,
  name text NOT NULL,
  original_title text,
  description text,
  category text,
  category_ids ARRAY,
  additional_categories ARRAY,
  phone text,
  url text,
  contact_url text,
  contributor_url text,
  book_online_url text,
  domain text,
  logo text,
  main_image text,
  total_photos integer,
  snippet text,
  address text,
  address_info jsonb,
  city text,
  zip text,
  region text,
  country_code text,
  latitude double precision,
  longitude double precision,
  is_claimed boolean,
  current_status text,
  is_directory_item boolean,
  price_level_text text,
  hotel_rating smallint,
  extras jsonb,
  business_info_raw jsonb,
  qna jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  place_topics jsonb,
  google_ratings jsonb,
  tripadvisor_ratings jsonb,
  CONSTRAINT external_places_pkey PRIMARY KEY (id)
);
CREATE TABLE public.raw_ingestions (
  id bigint NOT NULL DEFAULT nextval('raw_ingestions_id_seq'::regclass),
  provider text NOT NULL,
  endpoint text NOT NULL,
  task_id text,
  business_id uuid,
  external_place_id uuid,
  status text,
  check_url text,
  request_json jsonb,
  response_json jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT raw_ingestions_pkey PRIMARY KEY (id),
  CONSTRAINT raw_ingestions_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT raw_ingestions_external_place_id_fkey FOREIGN KEY (external_place_id) REFERENCES public.external_places(id)
);
CREATE TABLE public.review_aspect_insights (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  external_place_id uuid NOT NULL,
  aspect text NOT NULL,
  sentiment text NOT NULL CHECK (sentiment = ANY (ARRAY['positive'::text, 'neutral'::text, 'negative'::text])),
  mention_count integer NOT NULL DEFAULT 0,
  avg_severity numeric,
  gap_impact numeric,
  last_computed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT review_aspect_insights_pkey PRIMARY KEY (id),
  CONSTRAINT review_aspect_insights_external_place_id_fkey FOREIGN KEY (external_place_id) REFERENCES public.external_places(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  external_place_id uuid NOT NULL,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['google'::text, 'tripadvisor'::text])),
  provider_review_id text NOT NULL,
  rating_value numeric CHECK (rating_value >= 0::numeric AND rating_value <= 5::numeric),
  review_text text,
  original_review_text text,
  language text,
  original_language text,
  author_name text,
  profile_url text,
  profile_image_url text,
  local_guide boolean,
  reviewer_reviews_count integer,
  reviewer_photos_count integer,
  posted_at timestamp with time zone,
  review_url text,
  owner_answer text,
  original_owner_answer text,
  owner_posted_at timestamp with time zone,
  review_highlights jsonb,
  images jsonb,
  sentiment text CHECK (sentiment = ANY (ARRAY['positive'::text, 'neutral'::text, 'negative'::text])),
  aspects jsonb,
  review_item_raw jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  overall_score numeric,
  overall_sentiment_confidence numeric,
  gap_to_five boolean,
  gap_reasons ARRAY,
  critical_flags ARRAY,
  executive_summary text,
  action_items ARRAY,
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_external_place_id_fkey FOREIGN KEY (external_place_id) REFERENCES public.external_places(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['trial'::text, 'active'::text, 'past_due'::text, 'canceled'::text])),
  trial_ends_at timestamp with time zone,
  current_period_end timestamp with time zone,
  mp_preapproval_id text UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);